n = "ABabACacBCbca"

def create_map(notes):
    chars = {}
    for index, char in enumerate(notes):
        if char in chars:
            chars[char].append(index)
        else:
            chars[char] = [index]

    return chars

def find_all_pairs(notes):
    chars = create_map(notes)

    pairs = {}
    pairs['A'] = find_pairs(chars, 'A')
    pairs['B'] = find_pairs(chars, 'B')
    pairs['C'] = find_pairs(chars, 'C')

    return pairs

def find_pairs(chars, char):
    pairs = []
    for i in chars[char]:
        for j in chars[char.lower()]:
            if (j > i):
                pairs.append([i, j])

    return pairs

def find_limited_pairs(notes, limit):
    chars = create_map(notes)

    pairs = {}
    pairs['A'] = find_pairs_limit(chars, 'A', limit)
    pairs['B'] = find_pairs_limit(chars, 'B', limit)
    pairs['C'] = find_pairs_limit(chars, 'C', limit)

    return pairs

def find_pairs_limit(chars, char, limit):
    pairs = []
    for i in chars[char]:
        for j in chars[char.lower()]:
            if ((j > i and (j - i) <= limit) or (j < i and (i - j) <= limit)):
                pairs.append([i, j])

    return pairs

#n = "ABCaAABCBccCAaaCbaACCabbbaBBABaBcBcACACBAbaCBAbBaCaaAACaaBACAbabBABcCcbBAbBcbbBCaAcBcABCccAcaAaacBCB"
ps = find_all_pairs(n)
print(len(ps['A']))
n = "ABCCbABCAcabaCCBCAAcCbbCcbBAABBBAccBCacAACcBCAcCbBCabcCcbbcCabBcaAACAaABBBacCbBCCCacAaBBbBAbBbCCccCBCcAAbcCCCABaccBAaaaCcBbCBCaCABcACbCACabAcAACbACcABbBBBbbaaBaabACbABBCBAcCBbBaABbaAcACCBaCAccaaccBCBaccBBCCcaBbaaBbACaAAabccbaABaBABbbCBcbBACaCcCBBcbcbaaCbBbCbCBBCAAbaccaCbcCcBCBbACABAccBAcbbcCbAacbaAA"
print(len(ps['A']) + len(ps['B']) + len(ps['C']))

n = "AABCBABCABCabcabcABCCBAACBCa"
notes = n * 2
ps = find_limited_pairs(notes, 10)
print(len(ps['A']) + len(ps['B']) + len(ps['C']))

n = "accBcbbBBaaAbCaaabAcBaaACAcCcccBacCACbABaBAbbbccCbabBCbbbAcBaABcCAbBAccBCaACBCabaAbaabAbAcBcbBCcbcbbbbabCacBcCccAcAAaBAAcaCCcAaABbcccacCaAbcAaBAcccACacBCaaBbBCBcAAaccaBbBcAAccBabAcAbabaacbbabcCBBBAACbACbacabaaaCbbaabcCAbCabcbabCCbABCabAacACbCCbccaCcbabBbAccBcbCACaaAAcbCAbBAbcbccCcBBaaacAbBbCbccaBabABCbbBAaACAcabcACcaBbcABBaaBbBAABbBACAABaAacBBABabaaABCaBbAAAaAACaaAcAacbababBBCaABBacBbccCCbcBAACCaBAACccCbaBaBbcAaCCBCBCAcbBcbBBCcaCAbCAaaAccacCBabBAABCbcaaacACAACAABCACbbBBabACABbAcBAaCcAbBcAbcACbbaCBccABABbaAbcbccBAaBaBaaAcaBABabcbcbaaCAAbACBacbCbBcbcCbCaAbbccABccbACAcBaacACAbAbBcbBbCaBbacccCbBbacBbabcAaBACbacaaBCabCaACABBBbcAbbaaBaAABBabcbBaCbbacACacccbACcaBaBCBcaBCCcCcbCBcccacCaCCbBaaAaaAbABcaCccAaBBabCAabACAAaBCCBbBaCcbCCaBBaacbbbAAbcaaBCBcAbcABcCcABaCACbcAcBbABACcbBbBBcaBabAAAAaAaBcACABaaACCAAabBCCcAcBbaCBCcbaccccaabBBbacCaBCCBACbcaAcaBcCACcBcBCCACbCCaaCbbAaCbbcaACaBabCbbBaBCacbCbbAbACBbaaAacBabBaAacBaCacbCAccCCbcABAbAAAbbCbaACbBBacBcABAAACacAbabbCCBacaCaBAacaacaccCBaCbbaCCCcCcaaBAaBcCCbAcABaaAbbBbABBAAAbCccACbAbaCccABaBbBaABbcaCAacBcccAbAAcaCCAACBaacaBBcbacccbaaBcbBcaAAACCAcCBCcaCBbBCacaBAbCABCACABBBbbaBaCbBAcAaacbAAaAcaCBACbcBcBaABaBcbAaACacaCAacbBacCaCaCACbabAaacBAABCccACBBaCcbbAaCBBbAcAACAaAcaCBbbcAabAaCcaaAacAccbCcCAbcaCaccBCabbAcACaAcCCCbbAbABbCCbbaCbAAaCaCBcbcbaCbBcCAAaaCACCABabBbAABAbBbccaAbbCAAabCaBaAacACBBBBBbAbCAAAcbcccCABaCCCBCAAccacCcAaAbBaAbCBabCAbCAcCacABabcbaaAacCaCaCbbbaCCbCaabBABbCcbBBcABbacCcBAABBbBCaacbbAAbbcbCACcbBcbBCCAbbbbABCAAAaCBCBaBACAcbAaCbAcaAAcbcCcACCCAbBAAbBbBaBBbCbBaabBAcBACbCCaABaaBCacBCbAccCCacAaAaaACABcBCccBcAaBABBaAcbBBbaCacCacabAbcaAabABCAcBAAaabcbaBBBcBcABAcCAaaCBaBAabBbacBcBbAcbAAbAAcaaaCBccbBBaAabcAbBbbcCaacccCcCaAaBcbbcbaAAbaabcbBcAbABabbBcCBbAcCacaBaAbBCbaCAcbcCCcCbaABbaAcAcBCaCcAACcBcABAAaacAccCBBaacAbccabbaCcabBBAAbaAacaAbcBCbaBCbAAcaaccBbcCBaBbaaaAABAaBcaCccAaAaBaAbbCAcBAAAccaBaABBCCCBAcaAAcAACBcAcCCaBbBCCBcaCbccAcbaCacaCCAbaaAcbCAAAcBBAAbcccbCcbABBCCBBABacbBcbbaACAbCbBbaACbBABcbbbBcbcBBAAcBAABbBbccaCbBCabCbAcCBCbAcAAbaAABAaBBABcBABBaCbcaCacaAacCaCbBAABacbcaBBbcAcCbCCABcbcbCCaCCAbccCCAbbabBacCAcbBBcBACcCbBaaBcCbaacCabCcaAcbcaaABBAaBbAAccCaABBaCcaCaCaACbAAAcaabCCcCBcabBAAcacBabCCCbcaaCBBbCcbAcbCaabBabcBcCaaBBACCccabBbAAbBAAbbBBbAbbaCcABAbcbbcAcBBcCCcbaBbCcbbBACcBBbBcBbbBBbAaAaBcacCcCaAaCBcCcCaacAACcAbCbBABcCbBCcCaAaBAbCCCacaAbCAbBCaAbACCaBBcBcbCbcCCCbCbBBbBABbaaAcabcCacCaabbBabbcABcaBAAaaBbABCACCbaaAACCacAabBcbBCbcBcaaCbBaCcAcAACBBabCcaaAaaaCaCcBAAAacaAbacCaccCCCbCACbABcacbbBCcbaabBBBAaCAaCCCcaaaCAACCABBBAAcAbCcABacBCaaBcBCabCBCAaACaAcbcAAAcCBCcaccbaBaACBabaabCcAbBCbcaCccbCBCACAbabAABBCAbaccBcAaAAAbABABBBbBCCAbaAccccAbbaCcaacbabcCBBACaBACAAcbBCBCaCAABABcaCBCaCBBcBBcBaABAabaACcacCCABcbcaaaAaaBCABBCcbCbaaacCaabBAbbCCcbaaBaABbBcAacAcbbBbaBaacbAcACBccCAcBbbcaaAaBcAccBbBABABBBBBacBaaBcbCbCAACCCaCBBaCcBbBaCcbAabababaAaAAcBBbCcbBBbcACaBAaaACaCBbAaBbaaabaACabcAAcAcCabcbaAbaAcbcCacAbBBbcBCABbbCBCAaAcaBCBCBAAACACacabCCbaBBbacbaCbCCaBbABaBCaaAaaCAcabcaaaCbacbAAAbACBBaABAaacBaABcAaAABcabbBAcaCaaCBCababbccCaaACAAcBCBCBCcbAbBbccaAbbAacbbbaCbbcBbBAabcbCaAcAbcbcbCCaBBAccaccBbBbCCBAaAccaBBAaCAcbaBabAbccABBBCACbBAABcCcBACCccCBbcAaaBbbcABCBAbbcBcBaCcbaaAAccabAcbBabaCAaaBBcCBCccCBcaBBACcBBBBccABAcCbbcbCcCAAaAABbbBBaAcbABccabcbCBBAbcCCCCcCbaBAaBCbBCbABabaBabBabBaBCCcAABbccABBaBabababCCAabbbBaaBCbBcBccCAbbaabCcBABbbCBaBCabCCcabAACBcABAbcacaCCACBccAAcBCcCbCAbCBbBbAbbBccbbBbCbCAbBaccaCbBaBBBAcaBCCAAAcccBCCaAACacccCBAaBcbAAbAACAaCAacbcbaBACaCaBaabCccBBCBAAaAcBCaAACABaaAbcAAcBAbbAcbbbaACCaBaaaBAccCACCacCaAcBCbcBACbacbBacCAbACBbBBcaabCCcbbccAcAcaaaabcbcbCBBACAcCCBaaBAcABbaAbcAcbBAAaaAcBBABBbcabAbbacBcCbaAcBBaaBCbAbabBaCbCbCababbabaAcBCbabCBbACcbacbaAAaCaAbbaBAbBbAcaACbcbCaACaCBabbcbCcbBAAabBaCbbBcCcaccCAbAaBbACCbbCcaCaBBbbcbcbbBaaBaBACbcaCBaBbacbBcaAbAbbbACCcAABCbabCbaaBccCabbaAAbaBcAccBCCCcaabaabbcbBccBaCbabbcAAABccAcCbAbbBBaCcaBbBBaabCaCcBBCBbAaaBCBaAcBaccacaCacCaAACBacbCbbBbBBCcBcABcBaAaCcABbbBbaaaACcABaacBAbcAcbCaBaAaABbcbCcbccCCccbCaCcAccBCCaACAaaAaaBABcCBABcbACbABBBaccbABBAaCcBaaBbACbCaaacCAccaBcCCcAcABBCcCCAcaCbCcbCACbbCAaAbCBBbaaccBCBbBaccaACbccCcbbacbABcAcbBccCAAAcccCcaACCcbBBBaACBAcBcbCBbbAACACbcCBaaBAAbaACCABbCBaAcbaBcacBBAaAcCbACcABCACAACBAcBccaCCBbcbCaaBcacabbCBbaAbBBabCAabbAcaAACacBaAaCcBbBBcccbcbacACCBcCaaCaccabcbCCBAAbACaCcabCACbCcaaBCAcAbCAabAaaABACaAabbaBCaAABBCbbCABaBaBcBcCaccaccCcBcCCbAABBCbBccBBBBaBbbCABcbAcbBCBabbAaBbbBCbAcCCbaaBBBbACBAbcCcccbaCaaCAACbABacBCabaAbbaBbcAcBbBcbBABcCacaBbbaBbBaAAACCBaCcBbaAACbCCAcCbacAabbCAcabcAaABaBACbaBaCbaBaCbcCBcCcBbBcAcBCCabBCaBcbBbBaBABACAbaAcaCAaCCAccBaCbbaacBacacccAbAcbcbacBbCaCabaabcaBabaACcaAcAbbaCAcbCcabbBBabBBBBbACBAbbccCCcCbABacbBAccbbcaCbBcBbaCaAcaABAcaCcBaabBcccCAAcBccbCaBCAabAAaABabBAaACaBcCbBbAccCaAbbBcBBCBaaABBCABbbaABCbBcAAcACcaBbaCBBbACcCABCccaCcbcbbcbbaccBBAcCBaCAbBcBBBcbcAAacCCAACBaccCacbaaBccbacaBccccACaabBCbBBbcaaACBbACAaCaaBABbbBBaCCBbCCbBaacCBCbabaBbbBbaCcabcabaaCBbBAbCabbcBAaCbBabACbAabcbAcCBCbaCBABbccCAcabBCCBAbbABaCBCCABcBaCAbAbaBbCbCAAaBbBAccbbCabBbbaCcCcbABaaCccccCaBCBBCCBcbBaBABAbacaBAbBbcBaBabbBacAaaccccccCAacccAccbAbcbacCACAaaCCCaaaBCBcCBCaAcBABCbCcaBCCaAaBAAabaaCAACBcbBcccACCaCabccbaBacBAbABbCaAbaAaBbabBBaCacACBCABAAAbcbaaabCCAbcAbAcbbCCCBcCccCcCacabABACCCAAAABbbccBaCCCaCAabbCABcAbAAAaCCACAaCaaBbBbCBbCcAcABCCBcAAccaCBaCCcCBcAacAcaaABAaCBaAaccbaBcbBbbAcCBCCBCaCCcCcaaccCAcBCcbCABCbaACcaBAbAcBaabbAaaBbbabccCCcBBcAABbCbbBBbCaAAaAbAABbAaBcbaabAacbAACbaaCbcAAcCAcABcbABCbcabCaaacaaAcBbCaBbBcBbBaaAAcabCcbabCBaBbcBBBbccCAbbCCCacABcbaBcbBbCCCAcbcbcacaaBaBBBBcBbAbcCBbbAAaBBaCCabaaCabbcCcAabbcaCacACCABcCCBCcCCBbAabaBbBccbBbbBBBAbbAcbCccaAAACABACBCbaaBacAaaCbCCbABbbCcbBbAAbBBaBAACBcaBcaABBbbBabCaaccaBbbCabBbcBAbCccaaBcBACCCABcaaacBabbcCCcAcAccBAaCccCCaBCbACcabCcBaABbBBcbBABCabAbCAAccBbbBBbBbBBbccCAaCAcaAABCbccbaBbbCccaBaCAcabBAbBAbbbCbBbaabCcbCBbBCBCaaBCbBCBAaaBCbBbAbACcCCAAcAcbcBBbbABcBbaaaABaaabAbAaCBcBaCAccBAAcBbCbACbabABbCcaABBcCABCAbBcAcAabAACcaAcACbBBBBbCCbCABbcABAbBaABbAbAbcBBAABBCBcAaaabCACAaCBaAaaACCcCCbbaBCcbaaaCcCcCBABAAbBCcCCaBAccCCBCAaaABabcaaaCaCBBbaaBcbcaBAccCCccBCBBCCBBCcAacccCABbcACBabaCbCAaAbbaccbaCCcAaAABccCcAbbBabbCcACacabCCccbBCbCBaACaACcBbBBAcccBBBbAaacBbCcCAbCaaACbcaBcCBcBCacBcaaabbAcbaacAcCbBbabcCcCAcbacAaaAcBacaBaacbACAaABbcbbBbbAbBcbBbCcbaCacAbBacbcAbbCccBaabcCCBabAcbacACCAaCCCAaCbabBBaAacBaccbcbcBBcAcCACaABbBbAbaBBcCBCaBCCcaaAbbcACBbaAbABbaABBBABaCABABcBccAaCcAccbcaCcBcCACAbABbcBabaCAAcbbcbaBbcbBbaBBBacCcAbCBCBCcaaCCBBCbaBbcbaCcbBCBABAaaaAaCCbAabbCbcccCBAcabbAbbCaaAaBBbABBccACbaBBaCbBaBbaCCcCabcBCbbcCabACcbBAACcaccAcbbabbCCACABcCbaAaCbbcCACAbaACbbACaaABBAbbCcAaAbBcacBACcBAbccCcBbBACaabbbCBCBCCaAAcbbAAbcAcaABBbaabBbbbbccbcCccCCCbACCaccAbCaCcACBaabCaacACacbAbbCbaBCaBCAcCCaccCCAACCBBCaBBCbccacaCBAaCaAaAbBAABBcAbBAaaCcacbBCaaAbcCBCaAcBAACbcCACcAbaaaccccCaacaaBAcCCCCAaBaCCbaaABaabaacBBccBCCABbbcbCbaCAabccBaABBAabacaCBcAabCbcCBCabBACbBaaBbCaCbabbaBAaaACCCABBCAbbCbabBabaAccbAAaAaBaABAbBabacCccAabbbbBcbAAaBcAcbBcBCbAaBBBAbacbBCbAcCbBbacaBACbCBbBBAAaabBCCBbcAaCCaBcabBcabAcCCAAabBCBBBbCCBbAAcbcacaBCAcAcbbcccbBAaaBcaCaCbBBACBAacCABaAcACCAabbbaAABaabcACaCCabaccBCcCcaCAAAcAcCCCBbbBabABAACCbbBBBBcbBaBBBACbBbBbBaBcbBAAbCBAAaCbcCbccabababcbbaBbbBaaCbbbbABbbCbbCAaAbCBbAbbAbCAbcBcABaACaBcAaCCBbBaAbcCbBABCBCBAaBaAcbAaCABBbBaAcBAAaaaaCaAcCCaCCcabcCAbcaaBBBbCAAACBAAbCbbCCcAbBabaAccaCccCCAccCabAccabACcCcBcbAcCCBbBbBBaBcCcCCbbaCCaccbAcAbACbbBCaCAbCCCACabcbcAaBaaBcaCBCcCcaabaAAbaaCaCCbBbaCcAaaCbcaBaACAbaCCbbBCbCABbCAbBBcCaAaBBAcBBBbBcaaBACaBcBAccCaAcbAabaCcACcABaaBbBAAAaaCCccCcacCCbAabbbbCcCBCbaBccAcccBcBCccAaabcbbbABcBccaCaacbcCACCbaABaABAbAAabbbabaBccbBbCABccAcAcBBAABAbbBAccBBAbaBCCBbcBbBcBaBBABBBbACbBCbbbbBaaBCBCAcCAaBaCAaaBBBCcAaaCcAcbaBcBcCCbCBCcaCacCCAAABcCcabAbcCbAaBBAaABaACaACACAbbACcACBAAABBBccAacbBbCAABBAaaBaCbCbaCbacaaabBAACccbBccbbcAaCccCcAACABbBcBABAcCbCCBbAcCaBbccBbAACaccAaBCCcCCcbACabCCCCaBbbBbABaccBBbBBaAbbBCBcBABbaAcbCBcccACcccCBacbcaBcbbcAABBAabacbcCBABAABCAACBCbcAcaAbaABcbBABbaCCbBBbaAAaaccbbBBbABaBcacccbaabBbCbcaaacBbcaaCbAAcbaBbACcbcAabBCaaBBcAAAAbabAaACBBbcCACaAAaBBbAbCbCbACAAbbAcBcaaABBbCCbbccCBBBaabBabaBACcBCCbBcaBBcCabACaACBBAAAbaCbBbBccaBcCaaBbaBBAAacbBBacaBbcAcaABCCbCAaBBBbaabbCcabcBabCcbBCACcACbcCccACAaaacacBbaAbaccABbcAaBabccAcCaaBaaCCCAbcbcBAcbbcbCCbACAbACABBaBbABAACbBaAbAAAABBcBbaBCbBBcbbCcACBBbabBCbaaaACBBBaAcBccacabcABcAbcabBCbBbAbAcaBbbAAACacaBAcBacBaBbcAabbaAaAaBcbCcCbaAcAAaCcCBBBbacBCBcacaabBabcAABcbBCBaBCbBaBbaBbAcACBaABAacAbAbCCcaCaCcCACaCbcBccbCACCaCAAcbAaCBCBaCcBAAAcCaabbaCCcBbBcBAAbCcAbCcBBCabcaCBacABbBcBCABBBBcbbBbcaCbBbCcbbbCbBaBbcCcaAcAAaaBbaaaAccBCcACCACcACaCcAABaACabacCAAbcBCcacabcaBbbCaBBBcaBbcACBAaCACCabbAcBababACAACACCccBacaBccCCbCbbCAAbcbaABACaCAcaBAAcCbccccaccAcCCACaccaBCAaacCaAcbAABBBabAbAbBaACbbbCABCbbCBaAbABBabcbcBcbAabcBCcCCacbbCcCabBABBAcCaBcAAACACbBCbCabcCabbcBbCbcbcBcAAbcbaAbAcbABabbccAbBBBcCAacBcABAAbBaCbCAaccBAAaaABbbCCacBBCABacccBbbBBbBBbbbBcbacAbBcBAbAcAabABcCcBaACBaaBCaAaABacaACaccbCcAaabCCBCCBccaBBCBACBbcccBcACbBbaCAAaAAaccABBbBCABAcCCbbAaAacbbbCBacCCCcbcAcbBCBbcCCbbCBBBCAaAAaaAbbCcBabcBBCcBCcacBaCCCababaBACBcacABcabbAAccBbcaCbbBcBBaBCcAbcccbAcCCCbCbABbcbBbbCAcbBccAbbBccaCAccBBABaBCBAACaBaBcCCCBCCCBbAbAAABBCBccAbBacABAcBaAAccbaAcbBaBCBcCAAAAbaCaCabAbBCBcCbbCCcaCaCbbcbaAbcCCABaAccbCAbcAbCACcabaAacBbabcbAAaBaBbaCbaCCCCABBcAaBCbaaCccCCbAbbbabaCBcaaAabAbaacabCcAAABcaBcBaACABcCABbBBacaccAbaBCbaAaBAcbbaAbBCAaCcCbacAcabaACCAAaAbCCAbaACBcaCAbAcCBaaBcaaAaBBBBcAbAbcCaBCACABAcaccBAACcbBBBCacacBccAcbAaBccaAcAcccBcCCBabcCCcbBbbccaabBAcaACCAcaAabCBCAbaacabaBCCACAaacACCaBABbbbBBCCacbcBBAacBacbcbbcAcabBCbACAcCcAaaacbAbBcAaCCBaCCBBBABcbCbCAaBaCaCCBbABacaacbBcAbcAbcBaabaCbbccCaabcAcABbacacaBAcbcbAaaCaBCaCaAaaccBcBbbaABACbBABcbAbaBABBccBAbCCBCCbAAaCbBACCABCCBCABbCBaaACAaBbCbABABcCBBBbBCAbCcbcACcbabaBaCABaABBaAbbCabACBBbABBaabcaAaaAacCbcACAAaaccACbbbaBCACcCCCBaacCBAaaBbCCAcBBcABacaABbBcCCAbcBACaBBbccbCcBABbbAaBAbaaaccCBbABcbBCcaAbccCBCcabBAAcABacaCCbccCbaAAcACBBAAAcACbBcaBAbCBCBacAcabBBCbBcaaABacABBbAbBbcbBcbBaABaABbbCaAbaaCcBABBcAcBBccCbBCAbaccACAacCbaBaBAbcbBACCbccAACbBbCcCcacabBbCCccAcAbAaACBbcabCCbCbBaCBCCBabaBAbbcABCCBbcBACCCBbbAaAAaBbAaaABAcBBCCaCabaabCbbcaaabAbcaAAAA"
notes = n * 1
ps = find_limited_pairs(notes, 1000)
ans = len(ps['A']) + len(ps['B']) + len(ps['C']);
print(ans)
notes = n * 2
ps = find_limited_pairs(notes, 1000)
diff = len(ps['A']) + len(ps['B']) + len(ps['C']) - ans
print(ans + diff)
ans = ans + diff * 999
print(ans)
